### ISSUE TITLE
Does running Linux apps possible?

### ISSUE THREAD

**Issue by ClickNinYT** [danoon2/Boxedwine#32]
I mean, Boxedwine runs Wine, which is technically a Linux software. So I think running Debian based app should be possible too, isn't it?

**Comment by ClickNinYT** [comment]
Or running commands like "nano", "sudo", "apt", "ls", "dir", etc?

**Comment by danoon2** [comment]
In the early years of Boxedwine, it ran ran unmodified Wine, so a lot of the Linux stuff worked, including things like framebuffer (/dev/fb), XOrg, perl and dkpg.  But now Boxedwine talks to the host via a custom driver in Wine, a replacement for winex11.drv

It's been a couple of years since I tried to run just Linux apps, so /dev/fb might not work anymore even though it is still included in the code.  I would expect stuff like "ls", "gawk", "sed" to still work.  nano never worked because I didn't implement terminal support in the emulated kernel.  Currently you can pass command line arguments to the Linux app and see the output, but not interactive terminal stuff.

If you or someone else wants to enhance Boxedwine to have better Linux support I wouldn't mind helping guide that effort.  But I don't personally have plans to do that.  Right now my effort is just on improving support for Wine, things like like adding support for more platforms (Raspberry Pi, Mac M1), performance and 3D graphics.

**Comment by ClickNinYT** [comment]
I would really want to help but sadly, I don't know C, C++, or any language used in BoxedWine. I know some C#, so I wonder if that might help. I had a idea for running GUI apps by extract the file into rootFS and use commandline argument to trick BoxedWine to run that executable.

**Comment by ClickNinYT** [comment]
With some Linux GUI Apps and Terminal support, this could help Windows 7 users to ran Linux, use Wine or Darling and Anbox to run stuff. That will be cool.

**Comment by ClickNinYT** [comment]
Right now the tricking BoxedWine to run stuff is a bit impossible, since a lot of apps need additional packages to works.

**Comment by ClickNinYT** [comment]
I tried running a Appimage, but the cmd window just stuck there and nothing appears.

**Comment by ClickNinYT** [comment]
My Discord is ClickNin#4252, in case you want futher discussions.

**Comment by ClickNinYT** [comment]
It's me here, I have browsed though the repository and found that the oldest commit available is [here](https://github.com/danoon2/Boxedwine/commit/080205e1e3032514f7847e7e3836ae35cf851830). Can you guide me how to basically get BoxedWine to display a AppImage when run? I don't know C or C++, but I will try to learn along the way. Thanks

**Comment by danoon2** [comment]
I will look into creating an example that can run a simple UI application in XOrg.  It has been on my list of things to do for a while.  With any luck it won't require any code changes.  The hardest part is setting up the file system to include XOrg and all of its dependencies.  I creating some java code to help with this

https://github.com/danoon2/Boxedwine/blob/master/tools/debianFileSystem/src/org/boxedwine/Main.java

I think it will be just a matter of of me tweaking some stuff in there to get XOrg working.

**Comment by ClickNinYT** [comment]
I wondering, if BoxedWine can talk to host though a special driver, I think you can like trick all problems to talk though that driver too? Or is that will requires specific code changes in order to reach?

**Comment by ClickNinYT** [comment]
I created a discussion for this [here](https://github.com/danoon2/Boxedwine/discussions/36).

**Comment by ClickNinYT** [comment]
Closing in flavor of discussion.
