### ISSUE TITLE
Any plan to use GitHub Actions CI?

### ISSUE THREAD

**Issue by rwv** [danoon2/Boxedwine#46]
* Better integration than Jenkins
* Download built binary easily in GitHub Actions
* Better syntax than Jenkins (personal opinion)
* No need for self deployed Jenkins agent

**Comment by danoon2** [comment]
I started looking into it since someone wrote a script for the linux build

https://github.com/danoon2/Boxedwine/pull/35/commits/570c73c07e11a9b4015b0e4d35767e780f2a43b3

If I was only running on the 3 major platforms and had simple unit tests, GitHub Actions seems like the right choice.

But I have plans to run automation on all my platform where it will start Boxedwine, launch a program with Wine in Boxedwine and run it with simulated mouse and keyboard events and compare the screen shot results in a headless manner.  These can take a serious about of CPU and RAM.  In the past I had automation runs take over an hour that tested multiple apps and games.  I doubt GitHub would allow that :)

If it was easy to setup GitHub Actions with Raspberry Pi, Emscripten and Mac with an ARM chip, then I would consider using it for the main build and maybe running automation on Jenkins.  But I don't really want to spend much effort on it since I already need Jenkins.

**Comment by rwv** [comment]
I noticed that Raspberry Pi isn’t included in your Jenkins setup. Additionally, GitHub Actions supports Windows (x64), Linux (x64), and Mac (ARM), which might cover most of your current needs. If you’re interested, I can help with a PR to set up GitHub Actions for the main build process while keeping Jenkins for more specialized tasks. Let me know!

**Comment by danoon2** [comment]
@rwv Thanks, I think that sounds like a good idea.  I mainly had the Raspberry Pi's for Arm development, but now I do most of my Arm development on the M1 chip.  The Raspberry Pi's are cool, but they struggle with performance.  Maybe when the Raspberry Pi 6 comes out I will revisit them.  But for now I have I can do Linux Arm64 on the M1.
